### ISSUE TITLE
Glossary option is broken

### ISSUE THREAD

**Issue by theGrue** [LeoColomb/generator-latex#1]
Choosing the option to add a glossary results in the following error when compiling:

```
! LaTeX Error: File `../src/glos.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)

Enter file name: 
! Emergency stop.
<read *> 

l.31 \loadglsentries[main]{../src/glos}
                                       ^^M
!  ==> Fatal error occurred, no output PDF file produced!
```

An example bibliography is created, why not an example glossary?

**Comment by Overdrivr** [comment]
Hi, thanks for this repo.

I have issues with glossary not showing at the end. 

```bash
pdfTeX warning (dest): name {glo:computer} has been referenced but does not exist, replaced by a fixed one
```
I was missing perl for the `makeglossaries` command, I found that by running
```
grunt latex:gloss
```
But now it's fixed. Running this again claims another error:
```bash
Running "latex:gloss" (latex) task
[ 'makeglossaries',
  '-output-directory=C:\\Users\\*****\\Documents\\****\\phd\\dist',
  'phd.aux' ]
The file extension 'aux' doesn't correspond to any
known glossary extension. Try running makeglossaries
without an extension, e.g. makeglossaries "phd".
makeglossaries version 2.18 (2016-01-24)
added glossary type 'acronym' (alg,acr,acn)

Done, without errors.
```
In Gruntfile.js, I have removed `.aux`
```
gloss: {
        src: 'dist/phd',
        options: {
          engine: 'makeglossaries',
          interaction: false
        }
      }
```
And now, running the command again, I get no output
```
Running "latex:gloss" (latex) task

Done, without errors.
```

Any idea of how I can fix that ?

**Comment by Overdrivr** [comment]
I think I figured it out, you are configuring the task `latex:gloss` but no plugin is actually defining what it does, thus `makeglossaries` is never called.

I fixed the issue using the grunt-shell plugin to call directly `makeglossaries` command.

I can make a PR if you are interested, let me know.

**Comment by LeoColomb** [comment]
> grunt-shell plugin to call directly makeglossaries command

Is this solution cross-platform compatible? A common solution?

> I can make a PR if you are interested, let me know.

I'm always interested about a new PR! :smiley:

**Comment by LeoColomb** [comment]
@Overdrivr Any news? :kissing_cat:

**Comment by Overdrivr** [comment]
I believe `grunt-shell` works accross platforms (it is tested on Travis so it definitely works ok on Unix systems) and I am working on Windows. I suppose `makeglossaries` is also available on all platforms with Latex, but I am no expert. If it is, then yes it is cross-platform solution.
