### ISSUE TITLE
generation of pdf figures from svg files ?

### ISSUE THREAD

**Issue by Overdrivr** [LeoColomb/generator-latex#16]
Hi again,

Would you be interested in `.pdf` generation of svg figures using the `inkscape` command line ?

Basically, the user draws a figure in inkscape, saves it, grunt detects the changes and automatically creates a `.pdf` of the figure that can be easily imported inside the latex document.

Importing pdf rather than svg directly is a reliable way to import vector graphics inside a latex document. 

I believe this figure would be an awesome time-saver for large documents like PhD reports, where you are otherwise constantly re-running the pdf build command.

I can make a PR if you are interested.

**Comment by LeoColomb** [comment]
> Basically, the user draws a figure in inkscape, saves it, grunt detects the changes and automatically creates a .pdf of the figure that can be easily imported inside the latex document.

Very interesting! Thanks for sharing!

> I can make a PR if you are interested.

Always! :smile:

**Comment by Overdrivr** [comment]
Great !
So here is an overview of what I intend to do:

Add a `shell:figs` task to Gruntfile that will execute the inkscape command line on a given file 
Use the grunt watch event to modify the config of `shell:figs` dynamically to specificy the file it needs to be applied to

This alone should be enough to regenerate `.pdf` as the svg is being modified.
However, this cannot build all figures at once. I have looked with Grunt, and so far I haven't found a simple solution that allows me to execute a command for each file with grunt on a collection of files. (I have to say the fact that such a simple thing is not straightforward with grunt puzzles me a little, but anyway)

So, rather than fiddling around, I propose to write a simple js script that will find all svg files and execute the inkscape command using [`shelljs`](https://www.npmjs.com/package/shelljs) module.

Sounds good ?

**Comment by LeoColomb** [comment]
> modify the config of shell:figs dynamically to specificy the file it needs to be applied to

Hmm, a globbing patern isn't possible?

> command for each file with grunt on a collection of files.

A glob! :smile:
http://gruntjs.com/configuring-tasks#files

> Sounds good ?

Yes.

**Comment by Overdrivr** [comment]
I wanted to use a globbing pattern, then modify the command by passing for each file the filename, but I couldn't figure out how to make the grunt-shell module to do that. it should be possible, but with a pure js script it's 5 straightforward line of code :stuck_out_tongue: 

I'll make a PR then, you can always make some comments on the code if there are things you don't like ;)

BTW, good job on this generator, it is making me gain a lot of time on my phd writing !

**Comment by LeoColomb** [comment]
> but with a pure js script it's 5 straightforward line of code

Right.

> you can always make some comments on the code if there are things you don't like

Of course, ha ha!

> BTW, good job on this generator, it is making me gain a lot of time on my phd writing !

Cool, thanks for your feedback! :+1: 

Petite curiosité de ma part (donc réponse non obligatoire), quel est le sujet de votre thèse ? :smile:

**Comment by Overdrivr** [comment]
PR done

Mon sujet de thèse a un titre à coucher dehors, mais globalement a pour objectif d’améliorer la robustesse des circuits intégrés face aux décharges electro-statiques ;)

**Comment by Overdrivr** [comment]
Fixed by #17
