### ISSUE TITLE
'inkscape' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by darekf77** [LeoColomb/generator-latex#25]
**Platofrm windows**

What I've installed this:
- https://inkscape.org/en/download/windows/ for x64
- npm i -g inscape

Which should I use ?
...I am still getting errors after `grunt`:
```

'inkscape' is not recognized as an internal or external command,
operable program or batch file.
'inkscape' is not recognized as an internal or external command,
operable program or batch file.
'inkscape' is not recognized as an internal or external command,
operable program or batch file.
inkscape --file="node_modules/generator-latex/generators/app/templates/src/figure.svg" --export-pdf="node_modules/generator-latex/generators/app/templates/src/figure.pdf"
Command exited with code:  1
'inkscape' is not recognized as an internal or external command,
operable program or batch file.

inkscape --file="src/assets/figure.svg" --export-pdf="src/assets/figure.pdf"
Command exited with code:  1
'inkscape' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by LeoColomb** [comment]
Well, this time it's on your side. Verify that your `PATH` contains references to the inskape binaries.
Maybe restart your computer (to reload `PATH`).

**Comment by darekf77** [comment]
but which inkscape I should use ? This one from npm has no executable... and this one from webpage inkscape.exe is not working ...

```
PS C:\Users\Dariusz\Projects\...\_master_thesis> grunt
Running "execute:figs" (execute) task
-> executing C:\Users\Dariusz\Projects\...\_master_thesis\figs.js
inkscape --file="node_modules/inkscape/test/test.svg" --export-pdf="node_modules/inkscape/test/test.pdf"
Command exited with code:  0
inkscape --file="node_modules/generator-latex/generators/app/templates/src/figure.svg" --export-pdf="node_modules/generator-latex/generators/app/templates/src/figure.pdf"
Command exited with code:  0
inkscape --file="src/assets/figure.svg" --export-pdf="src/assets/figure.pdf"
Command exited with code:  0
-> completed C:\Users\Dariusz\Projects\...\_master_thesis\figs.js (1162ms)

>> 1 file and 0 calls executed (1167ms)

Running "connect:server" (connect) task
Started connect web server on http://localhost:8000

Running "watch" task
Waiting...
```

and in browser I still have

> Cannot GET /master-thesis.pdf

**Comment by LeoColomb** [comment]
Maybe @Overdrivr knows?

**Comment by Overdrivr** [comment]
It is indeed the official inkscape version that should be used and not the one from NPM.

Actually your log looks good, the command returns 0 which means everything ran ok. I feel like everything is running properly.
Have you checked inside the folder if the `.pdf` figure files were created ?

I often get the issue `Cannot GET /master-thesis.pdf` it is not related to the inkscape task, I think you just need to reload the page. 

Personnally, I remove the task that opens the browser, and I open the final pdf with a regular pdf reader (like [Sumatra PDF](https://www.sumatrapdfreader.org/free-pdf-reader-fr.html) (webpage doesnt look good but it's probably the BEST pdf reader out there).

One nice perk, automatic reload: if you are somewhere on the PDF and it gets updated in the background, you get automatic reload out of the box.
